# Generated by Django 4.0.6 on 2022-08-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_plan',
            fields=[
                ('plan_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Duration', models.CharField(max_length=45)),
                ('Charge', models.IntegerField(default=0)),
                ('Description', models.TextField()),
            ],
        ),
    ]
