# Generated by Django 4.0.6 on 2022-08-07 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_coach_detail_rename_charge_membership_plan_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('your_query', models.TextField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
